workflows:
  android:
    name: OmniOffice Build
    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
